# Generated by Django 4.2.3 on 2023-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_pricetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetext',
            name='pc_place',
            field=models.CharField(max_length=55, null=True, verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='pricetext',
            name='pc_style',
            field=models.CharField(max_length=200, null=True, verbose_name='Style'),
        ),
    ]
