# Generated by Django 4.2.3 on 2023-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_pricetext_pc_place_pricetext_pc_style'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceCard',
        ),
        migrations.AddField(
            model_name='pricetext',
            name='pc_price',
            field=models.CharField(max_length=55, null=True, verbose_name='Price'),
        ),
    ]
