# Generated by Django 4.2.3 on 2023-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_delete_pricecard_pricetext_pc_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_value', models.CharField(max_length=20, verbose_name='Price')),
                ('pc_description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.DeleteModel(
            name='PriceText',
        ),
    ]
